# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

#### ESTE CODIGO SIRVE PARA AUTENTICAR CON BASE DE DATOS ####
    encoders:
        AppBundle\Entity\User: bcrypt
    providers:
        database_users:
            entity: { class: AppBundle:User, property: username }

#### ESTE CODIGO SIRVE PARA AUTENTICAR IN MEMORY ####
#    encoders:
#        Symfony\Component\Security\Core\User\User: plaintext
#    providers:
#        in_memory:
#            memory:
#                users:
#                    benatespina: { password: 'escuelait', roles: 'ROLE_ADMIN' }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            guard:
                authenticators:
                    - app.form_login_authenticator
            logout:
                path:   /logout
                target: /login

            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }

